// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"ffmpeg-exmple/controller"
	"ffmpeg-exmple/service"
)

// Injectors from wire.go:

func InitVideoController(service2 service.VideoService) controller.VideoController {
	videoController := controller.ProvideVideoController(service2)
	return videoController
}
